name: CI

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Install requirements
        run: sudo apt-get install -y --no-install-recommends shellcheck

      - uses: actions/checkout@v2

      - name: Lint
        run: shellcheck bin/excel2csv
